Pre-commit hook

diff --git a/scripts/githooks/pre-commit b/scripts/githooks/pre-commit
--- a/scripts/githooks/pre-commit
+++ b/scripts/githooks/pre-commit
@@ -1,5 +1,14 @@
 #!/bin/sh
 
+function failCommit() {
+    tput setaf 1
+    echo "----------------------------------------"
+    echo "FATAL ERROR: $1"
+    echo "----------------------------------------"
+    tput sgr0
+    exit 1
+}
+
 # A pre-commit hook for git to lint JavaScript files with jshint
 # @see https://github.com/jshint/jshint/
 
@@ -21,10 +30,12 @@ for FILE in `git diff-index --name-only ${against} -- | egrep *.js`; do
     # env/ddc-jsc.sh ${REPO}/${FILE}
     
     # could similarly wrap Rhino or Node...
-    jshint ${FILE}
+    jshint ${REPO}/${FILE}
     
     EXIT_CODE=$((${EXIT_CODE} + $?))
 done
+
+failCommit "Unable To Commit"
 
 if [[ ${EXIT_CODE} -ne 0 ]]; then
     echo ""
